### ISSUE TITLE
Get publishing of test results working 

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/WpfColorHelper#1]
Need to understand how to address this failure:

```ascii
Publish Test Results
  2024-11-16 09:20:15 +0000 - publish -  INFO - Available memory to read files: 13.6 GiB
  2024-11-16 09:20:15 +0000 - publish -  INFO - Reading files testresults\**\*.trx (1 file, 6.4 KiB)
  2024-11-16 09:20:15 +0000 - publish -  INFO - Detected 1 TRX file (6.4 KiB)
  2024-11-16 09:20:15 +0000 - publish -  INFO - Finished reading 1 files in 0.02 seconds
  2024-11-16 09:20:15 +0000 - publish -  INFO - Publishing success results for commit d9f5dd204a85e4c40157669be2a25858cb40d8b9
  Request POST /repos/mrlacey/WpfColorHelper/check-runs failed with 403: Forbidden
  2024-11-16 09:20:17 +0000 - github.GithubRetry -  INFO - Request POST /repos/mrlacey/WpfColorHelper/check-runs failed with 403: Forbidden
  Traceback (most recent call last):
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish_test_results.py", line 546, in <module>
      main(settings, gha)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish_test_results.py", line 269, in main
      Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish\publisher.py", line 233, in publish
      data = self.publish_check(data)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish\publisher.py", line 461, in publish_check
      check_run = self._repo.create_check_run(name=self._settings.check_name,
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Repository.py", line 3885, in create_check_run
      headers, data = self._requester.requestJsonAndCheck(
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 550, in requestJsonAndCheck
      return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 715, in requestJson
      return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 812, in __requestEncode
      status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 846, in __requestRaw
      response = cnx.getresponse()
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 198, in getresponse
      r = verb(
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 637, in post
      return self.request("POST", url, data=data, json=json, **kwargs)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 589, in request
      resp = self.send(prep, **send_kwargs)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 703, in send
      r = adapter.send(request, **kwargs)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\requests\adapters.py", line 667, in send
      resp = conn.urlopen(
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\urllib3\connectionpool.py", line 934, in urlopen
      retries = retries.increment(method, url, response=response, _pool=self)
    File "D:\a\WpfColorHelper\WpfColorHelper\enricomi-publish-action-venv\lib\site-packages\github\GithubRetry.py", line 187, in increment
      raise Requester.createException(response.status, response.headers, content)  # type: ignore
  github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run", "status": "403"}
```

**Comment by mrlacey** [comment]
fixed it
